import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as s3n from 'aws-cdk-lib/aws-s3-notifications';
import * as cr from 'aws-cdk-lib/custom-resources';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as path from 'path';
import { Construct } from 'constructs';

export interface EcsLogGatewayV2Props {
  readonly gatewayName?: string;
  readonly cognitoUserPoolName?: string;
  readonly resourceServerName?: string;
  readonly logRetentionDays?: number;
  readonly enableKmsEncryption?: boolean;
  readonly sopBucketName?: string;

  /**
   * Explicit list of AWS regions permitted for cross-region SSM execution.
   * Used for IAM aws:RequestedRegion conditions and Lambda ALLOWED_REGIONS env var.
   * @default [Stack region]
   */
  readonly allowedRegions?: string[];

  /**
   * IAM role ARNs for ECS container instances that need KMS encrypt and S3 PutObject access.
   * When provided, replaces AnyPrincipal/AccountRootPrincipal with these specific roles.
   * When omitted, backward-compatible permissive policies are retained.
   * @default undefined (backward-compatible mode)
   */
  readonly ecsInstanceRoleArns?: string[];

  /**
   * Presigned URL expiration in seconds for all S3 presigned URLs generated by the Lambda.
   * @default 900
   */
  readonly presignedUrlExpirationSeconds?: number;

  /**
   * IAM role ARN for the SSM Default Host Management Configuration role.
   * This role needs S3 PutObject and KMS Encrypt to upload collected logs.
   * @default undefined
   */
  readonly ssmDefaultHostRoleArn?: string;
}

export class EcsLogGatewayConstructV2 extends Construct {
  public readonly logsBucket: s3.Bucket;
  public readonly kmsKey: kms.Key | undefined;
  public readonly ssmAutomationFunction: lambda.Function;
  public readonly unzipFunction: lambda.Function;
  public readonly findingsIndexerFunction: lambda.Function;
  public readonly userPool: cognito.UserPool;
  public readonly userPoolClient: cognito.UserPoolClient;
  public readonly ssmAutomationRole: iam.Role;
  public readonly gatewayExecutionRole: iam.Role;
  public readonly sopBucket: s3.Bucket;

  constructor(scope: Construct, id: string, props: EcsLogGatewayV2Props = {}) {
    super(scope, id);

    const gatewayName = props.gatewayName ?? 'EcsInstanceLogMcpGW';
    const cognitoUserPoolName = props.cognitoUserPoolName ?? 'ecs-log-gateway-pool';
    const resourceServerName = props.resourceServerName ?? 'ecs-log-gateway-id';
    const logRetentionDays = props.logRetentionDays ?? 1;
    const enableKmsEncryption = props.enableKmsEncryption ?? true;

    // Default allowedRegions to the stack's region if not provided or empty
    const allowedRegions = (props.allowedRegions && props.allowedRegions.length > 0)
      ? props.allowedRegions
      : [cdk.Stack.of(this).region];

    // ========================================================================
    // KMS KEY (Optional)
    // ========================================================================
    if (enableKmsEncryption) {
      this.kmsKey = new kms.Key(this, 'LogsEncryptionKey', {
        alias: `${cdk.Stack.of(this).stackName}-logs-key`,
        description: 'KMS key for ECS log encryption',
        enableKeyRotation: true,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      });

      this.kmsKey.addToResourcePolicy(new iam.PolicyStatement({
        sid: 'AllowEC2InstancesEncrypt',
        effect: iam.Effect.ALLOW,
        principals: [new iam.AccountRootPrincipal()],
        actions: ['kms:Encrypt', 'kms:GenerateDataKey*'],
        resources: ['*'],
        conditions: {
          StringEquals: { 'aws:PrincipalAccount': cdk.Stack.of(this).account },
        },
      }));

      // KMS key policy for ECS container instance uploads
      const ecsInstanceRoleArns = props.ecsInstanceRoleArns;
      if (ecsInstanceRoleArns && ecsInstanceRoleArns.length > 0) {
        // Tight policy: grant encrypt-only to specific ECS instance role ARNs
        this.kmsKey.addToResourcePolicy(new iam.PolicyStatement({
          sid: 'AllowECSInstanceRolesEncrypt',
          effect: iam.Effect.ALLOW,
          principals: ecsInstanceRoleArns.map(arn => new iam.ArnPrincipal(arn)),
          actions: ['kms:GenerateDataKey', 'kms:Encrypt'],
          resources: ['*'],
        }));
      } else {
        // Backward-compatible: AnyPrincipal with account condition, reduced to encrypt-only actions
        this.kmsKey.addToResourcePolicy(new iam.PolicyStatement({
          sid: 'AllowAccountPrincipalsEncrypt',
          effect: iam.Effect.ALLOW,
          principals: [new iam.AnyPrincipal()],
          actions: ['kms:GenerateDataKey', 'kms:GenerateDataKey*', 'kms:Encrypt'],
          resources: ['*'],
          conditions: {
            StringEquals: {
              'aws:PrincipalAccount': cdk.Stack.of(this).account,
            },
          },
        }));
      }

      // Grant SSM Default Host Management role KMS encrypt access
      if (props.ssmDefaultHostRoleArn) {
        this.kmsKey.addToResourcePolicy(new iam.PolicyStatement({
          sid: 'AllowSSMDefaultHostRoleEncrypt',
          effect: iam.Effect.ALLOW,
          principals: [new iam.ArnPrincipal(props.ssmDefaultHostRoleArn)],
          actions: ['kms:GenerateDataKey', 'kms:Encrypt'],
          resources: ['*'],
        }));
      }
    }

    // ========================================================================
    // IAM ROLES
    // ========================================================================
    this.ssmAutomationRole = new iam.Role(this, 'SSMAutomationRole', {
      roleName: `${cdk.Stack.of(this).stackName}-ssm-automation-role`,
      assumedBy: new iam.ServicePrincipal('ssm.amazonaws.com'),
    });

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'ssm:StartAutomationExecution', 'ssm:StopAutomationExecution',
        'ssm:GetAutomationExecution', 'ssm:DescribeAutomationExecutions',
        'ssm:SendCommand', 'ssm:GetCommandInvocation',
        'ssm:ListCommandInvocations', 'ssm:ListCommands',
        'ssm:CancelCommand', 'ssm:GetDocument', 'ssm:DescribeDocument',
        'ssm:DescribeInstanceInformation',
      ],
      resources: ['*'],
    }));

    this.ssmAutomationRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'ec2:DescribeInstances', 'ec2:DescribeTags', 'ec2:DescribeInstanceStatus',
        'ecs:DescribeClusters', 'ecs:ListClusters',
        'ecs:DescribeContainerInstances', 'ecs:ListContainerInstances',
      ],
      resources: ['*'],
    }));

    // ========================================================================
    // S3 BUCKET
    // ========================================================================
    const bucketProps: s3.BucketProps = {
      bucketName: `${cdk.Stack.of(this).stackName.toLowerCase()}-logs-${cdk.Stack.of(this).account}`,
      versioned: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      lifecycleRules: [
        { id: 'DeleteOldLogs', enabled: true, expiration: cdk.Duration.days(logRetentionDays) },
        { id: 'DeleteOldIdempotencyMappings', enabled: true, prefix: 'idempotency/', expiration: cdk.Duration.days(7) },
        { id: 'DeleteOldExecutionRegionMappings', enabled: true, prefix: 'execution-regions/', expiration: cdk.Duration.days(7) },
        { id: 'ExpireOldBaselines', enabled: true, prefix: 'baselines/', expiration: cdk.Duration.days(90) },
      ],
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    };

    if (this.kmsKey) {
      Object.assign(bucketProps, { encryption: s3.BucketEncryption.KMS, encryptionKey: this.kmsKey, bucketKeyEnabled: true });
    } else {
      Object.assign(bucketProps, { encryption: s3.BucketEncryption.S3_MANAGED });
    }

    this.logsBucket = new s3.Bucket(this, 'LogsBucket', bucketProps);
    this.logsBucket.grantReadWrite(this.ssmAutomationRole);
    if (this.kmsKey) {
      this.kmsKey.grantEncryptDecrypt(this.ssmAutomationRole);
    }

    // S3 bucket policy: scope to specific instance roles if provided
    const uploadPrincipals: iam.IPrincipal[] = (props.ecsInstanceRoleArns && props.ecsInstanceRoleArns.length > 0)
      ? props.ecsInstanceRoleArns.map(arn => new iam.ArnPrincipal(arn))
      : [new iam.AccountRootPrincipal()];

    // Add SSM Default Host Management role if provided
    if (props.ssmDefaultHostRoleArn) {
      uploadPrincipals.push(new iam.ArnPrincipal(props.ssmDefaultHostRoleArn));
    }

    this.logsBucket.addToResourcePolicy(new iam.PolicyStatement({
      sid: 'AllowEC2InstancesUpload',
      effect: iam.Effect.ALLOW,
      principals: uploadPrincipals,
      actions: ['s3:PutObject', 's3:GetBucketPolicyStatus', 's3:GetBucketAcl'],
      resources: [this.logsBucket.bucketArn, `${this.logsBucket.bucketArn}/*`],
      conditions: { StringEquals: { 'aws:PrincipalAccount': cdk.Stack.of(this).account } },
    }));

    // ========================================================================
    // FINDINGS INDEXER LAMBDA (triggered by Unzip after extraction)
    // ========================================================================
    const findingsIndexerRole = new iam.Role(this, 'FindingsIndexerRole', {
      roleName: `${cdk.Stack.of(this).stackName}-findings-indexer-role`,
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
    });
    this.logsBucket.grantReadWrite(findingsIndexerRole);
    if (this.kmsKey) { this.kmsKey.grantEncryptDecrypt(findingsIndexerRole); }

    this.findingsIndexerFunction = new lambda.Function(this, 'FindingsIndexerFunction', {
      functionName: `${cdk.Stack.of(this).stackName}-findings-indexer`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'index.lambda_handler',
      role: findingsIndexerRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 1024,
      environment: { LOGS_BUCKET_NAME: this.logsBucket.bucketName },
      code: lambda.Code.fromInline(this.getFindingsIndexerCode()),
      logRetention: logs.RetentionDays.TWO_WEEKS,
    });

    // ========================================================================
    // UNZIP LAMBDA (triggers Findings Indexer after extraction)
    // ========================================================================
    const unzipLambdaRole = new iam.Role(this, 'UnzipLambdaRole', {
      roleName: `${cdk.Stack.of(this).stackName}-unzip-lambda-role`,
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
    });
    this.logsBucket.grantReadWrite(unzipLambdaRole);
    if (this.kmsKey) { this.kmsKey.grantEncryptDecrypt(unzipLambdaRole); }
    this.findingsIndexerFunction.grantInvoke(unzipLambdaRole);

    this.unzipFunction = new lambda.Function(this, 'UnzipFunction', {
      functionName: `${cdk.Stack.of(this).stackName}-unzip-function`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'index.lambda_handler',
      role: unzipLambdaRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 1024,
      environment: { FINDINGS_INDEXER_FUNCTION: this.findingsIndexerFunction.functionName },
      code: lambda.Code.fromInline(this.getUnzipLambdaCode()),
      logRetention: logs.RetentionDays.TWO_WEEKS,
    });

    this.logsBucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.LambdaDestination(this.unzipFunction), { suffix: '.zip' });
    this.logsBucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.LambdaDestination(this.unzipFunction), { suffix: '.tar.gz' });

    // ========================================================================
    // SSM AUTOMATION LAMBDA
    // ========================================================================
    const lambdaExecutionRole = new iam.Role(this, 'LambdaExecutionRole', {
      roleName: `${cdk.Stack.of(this).stackName}-lambda-execution-role`,
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
    });

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'ssm:StartAutomationExecution', 'ssm:GetAutomationExecution',
        'ssm:DescribeAutomationExecutions', 'ssm:StopAutomationExecution',
        'ssm:DescribeInstanceInformation', 'ssm:ListCommands', 'ssm:ListCommandInvocations',
      ],
      resources: ['*'],
    }));

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      sid: 'SSMDocumentAccess',
      effect: iam.Effect.ALLOW,
      actions: ['ssm:GetDocument', 'ssm:DescribeDocument'],
      resources: [
        `arn:aws:ssm:*::document/AWSSupport-CollectECSInstanceLogs`,
        `arn:aws:ssm:*:${cdk.Stack.of(this).account}:document/*`,
      ],
    }));

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: [
        'ec2:DescribeInstances', 'ec2:DescribeRegions', 'ec2:DescribeTags',
        'ec2:DescribeInstanceStatus', 'ec2:DescribeNetworkInterfaces',
        'ec2:DescribeSubnets', 'ec2:DescribeSecurityGroups', 'ec2:DescribeRouteTables',
        'ecs:DescribeClusters', 'ecs:ListClusters',
        'ecs:DescribeContainerInstances', 'ecs:ListContainerInstances',
        'ecs:DescribeServices', 'ecs:ListServices',
        'ecs:DescribeTasks', 'ecs:ListTasks',
        'ssm:DescribeInstanceInformation',
        'autoscaling:DescribeAutoScalingGroups',
      ],
      resources: ['*'],
    }));

    this.logsBucket.grantReadWrite(lambdaExecutionRole);
    if (this.kmsKey) { this.kmsKey.grantEncryptDecrypt(lambdaExecutionRole); }

    lambdaExecutionRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['iam:PassRole'],
      resources: [this.ssmAutomationRole.roleArn],
      conditions: { StringEquals: { 'iam:PassedToService': 'ssm.amazonaws.com' } },
    }));

    const lambdaEnv: { [key: string]: string } = {
      LOGS_BUCKET_NAME: this.logsBucket.bucketName,
      SSM_AUTOMATION_ROLE_ARN: this.ssmAutomationRole.roleArn,
      ALLOWED_REGIONS: allowedRegions.join(','),
      PRESIGNED_URL_EXPIRATION_SECONDS: String(props.presignedUrlExpirationSeconds ?? 900),
    };
    if (this.kmsKey) { lambdaEnv['KMS_KEY_ARN'] = this.kmsKey.keyArn; }

    // SOP Bucket
    this.sopBucket = new s3.Bucket(this, 'SOPBucket', {
      bucketName: props.sopBucketName ?? `${cdk.Stack.of(this).stackName.toLowerCase()}-sops-${cdk.Stack.of(this).account}`,
      versioned: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });
    lambdaEnv['SOP_BUCKET_NAME'] = this.sopBucket.bucketName;
    this.sopBucket.grantRead(lambdaExecutionRole);

    // Auto-deploy SOP runbooks from local sops/ directory to the SOP bucket
    new s3deploy.BucketDeployment(this, 'SOPDeployment', {
      sources: [s3deploy.Source.asset(path.join(__dirname, '../', 'sops'))],
      destinationBucket: this.sopBucket,
      prune: true,
    });

    this.ssmAutomationFunction = new lambda.Function(this, 'SSMAutomationFunction', {
      functionName: `${cdk.Stack.of(this).stackName}-ssm-automation`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'ecs-log-automation.lambda_handler',
      role: lambdaExecutionRole,
      timeout: cdk.Duration.minutes(5),
      memorySize: 1024,
      environment: lambdaEnv,
      code: lambda.Code.fromAsset(path.join(__dirname, 'lambda')),
      logRetention: logs.RetentionDays.TWO_WEEKS,
    });

    // ========================================================================
    // GATEWAY EXECUTION ROLE
    // ========================================================================
    this.gatewayExecutionRole = new iam.Role(this, 'GatewayExecutionRole', {
      roleName: `${cdk.Stack.of(this).stackName}-gateway-execution-role`,
      assumedBy: new iam.ServicePrincipal('bedrock-agentcore.amazonaws.com'),
    });

    this.gatewayExecutionRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['lambda:InvokeFunction'],
      resources: [this.ssmAutomationFunction.functionArn],
    }));

    this.gatewayExecutionRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
      resources: ['*'],
    }));

    this.ssmAutomationFunction.addPermission('AllowAgentCoreInvoke', {
      principal: new iam.ServicePrincipal('bedrock-agentcore.amazonaws.com'),
      action: 'lambda:InvokeFunction',
      sourceAccount: cdk.Stack.of(this).account,
    });

    // ========================================================================
    // COGNITO - Authentication
    // ========================================================================
    this.userPool = new cognito.UserPool(this, 'UserPool', {
      userPoolName: cognitoUserPoolName,
      passwordPolicy: { minLength: 8, requireUppercase: false, requireLowercase: false, requireDigits: false, requireSymbols: false },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const resourceServer = new cognito.UserPoolResourceServer(this, 'ResourceServer', {
      userPool: this.userPool,
      identifier: resourceServerName,
      scopes: [
        { scopeName: 'gateway:read', scopeDescription: 'Read access to gateway' },
        { scopeName: 'gateway:write', scopeDescription: 'Write access to gateway' },
      ],
    });

    this.userPoolClient = new cognito.UserPoolClient(this, 'UserPoolClient', {
      userPool: this.userPool,
      userPoolClientName: 'ecs-log-gateway-client',
      generateSecret: true,
      oAuth: {
        flows: { clientCredentials: true },
        scopes: [
          cognito.OAuthScope.custom(`${resourceServerName}/gateway:read`),
          cognito.OAuthScope.custom(`${resourceServerName}/gateway:write`),
        ],
      },
      supportedIdentityProviders: [cognito.UserPoolClientIdentityProvider.COGNITO],
    });
    this.userPoolClient.node.addDependency(resourceServer);

    const userPoolDomain = new cognito.UserPoolDomain(this, 'UserPoolDomain', {
      userPool: this.userPool,
      cognitoDomain: { domainPrefix: `${cdk.Stack.of(this).stackName.toLowerCase()}-${cdk.Stack.of(this).account}` },
    });

    // ========================================================================
    // CLIENT SECRET RETRIEVAL
    // ========================================================================
    const clientSecretRetrieverRole = new iam.Role(this, 'ClientSecretRetrieverRole', {
      roleName: `${cdk.Stack.of(this).stackName}-secret-retriever-role`,
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')],
    });
    clientSecretRetrieverRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['cognito-idp:DescribeUserPoolClient'],
      resources: [this.userPool.userPoolArn],
    }));

    const clientSecretRetrieverFunction = new lambda.Function(this, 'ClientSecretRetrieverFunction', {
      functionName: `${cdk.Stack.of(this).stackName}-secret-retriever`,
      runtime: lambda.Runtime.PYTHON_3_11,
      handler: 'index.handler',
      role: clientSecretRetrieverRole,
      timeout: cdk.Duration.seconds(30),
      code: lambda.Code.fromInline(this.getClientSecretRetrieverCode()),
    });

    const clientSecretRetriever = new cr.AwsCustomResource(this, 'ClientSecretRetriever', {
      onCreate: {
        service: 'Lambda', action: 'invoke',
        parameters: {
          FunctionName: clientSecretRetrieverFunction.functionName,
          Payload: JSON.stringify({
            RequestType: 'Create',
            ResourceProperties: { UserPoolId: this.userPool.userPoolId, ClientId: this.userPoolClient.userPoolClientId },
          }),
        },
        physicalResourceId: cr.PhysicalResourceId.of('ClientSecretRetriever'),
      },
      policy: cr.AwsCustomResourcePolicy.fromStatements([
        new iam.PolicyStatement({ actions: ['lambda:InvokeFunction'], resources: [clientSecretRetrieverFunction.functionArn] }),
      ]),
    });
    clientSecretRetriever.node.addDependency(this.userPoolClient);

    // ========================================================================
    // AGENTCORE GATEWAY
    // ========================================================================
    const gateway = new cdk.CfnResource(this, 'AgentCoreGateway', {
      type: 'AWS::BedrockAgentCore::Gateway',
      properties: {
        Name: gatewayName,
        Description: 'ECS Instance Log Collection MCP Server with pre-indexed findings, byte-range streaming, and incident analysis',
        ProtocolType: 'MCP',
        AuthorizerType: 'CUSTOM_JWT',
        AuthorizerConfiguration: {
          CustomJWTAuthorizer: {
            AllowedClients: [this.userPoolClient.userPoolClientId],
            DiscoveryUrl: `https://cognito-idp.${cdk.Stack.of(this).region}.amazonaws.com/${this.userPool.userPoolId}/.well-known/openid-configuration`,
          },
        },
        RoleArn: this.gatewayExecutionRole.roleArn,
      },
    });
    gateway.node.addDependency(this.userPoolClient);
    gateway.node.addDependency(userPoolDomain);

    const gatewayTarget = new cdk.CfnResource(this, 'LambdaGatewayTarget', {
      type: 'AWS::BedrockAgentCore::GatewayTarget',
      properties: {
        GatewayIdentifier: gateway.ref,
        Name: 'ECSInstanceLogTarget',
        Description: 'ECS Instance Log Collection Target',
        TargetConfiguration: {
          Mcp: {
            Lambda: {
              LambdaArn: this.ssmAutomationFunction.functionArn,
              ToolSchema: { InlinePayload: this.getToolSchemaDefinitions() },
            },
          },
        },
        CredentialProviderConfigurations: [{ CredentialProviderType: 'GATEWAY_IAM_ROLE' }],
      },
    });
    gatewayTarget.node.addDependency(this.ssmAutomationFunction);
    gatewayTarget.node.addDependency(this.gatewayExecutionRole);

    // ========================================================================
    // OUTPUTS
    // ========================================================================
    new cdk.CfnOutput(this, 'GatewayId', { description: 'ID of the AgentCore Gateway', value: gateway.ref, exportName: `${cdk.Stack.of(this).stackName}-GatewayId` });
    new cdk.CfnOutput(this, 'GatewayUrl', { description: 'MCP Server URL', value: gateway.getAtt('GatewayUrl').toString(), exportName: `${cdk.Stack.of(this).stackName}-GatewayUrl` });
    new cdk.CfnOutput(this, 'CognitoUserPoolId', { description: 'Cognito User Pool ID', value: this.userPool.userPoolId, exportName: `${cdk.Stack.of(this).stackName}-CognitoUserPoolId` });
    new cdk.CfnOutput(this, 'CognitoClientId', { description: 'OAuth Client ID', value: this.userPoolClient.userPoolClientId, exportName: `${cdk.Stack.of(this).stackName}-CognitoClientId` });
    new cdk.CfnOutput(this, 'OAuthExchangeUrl', { description: 'OAuth Token URL', value: `https://${cdk.Stack.of(this).stackName.toLowerCase()}-${cdk.Stack.of(this).account}.auth.${cdk.Stack.of(this).region}.amazoncognito.com/oauth2/token`, exportName: `${cdk.Stack.of(this).stackName}-OAuthExchangeUrl` });
    new cdk.CfnOutput(this, 'OAuthScope', { description: 'OAuth Scope', value: `${resourceServerName}/gateway:read`, exportName: `${cdk.Stack.of(this).stackName}-OAuthScope` });
    new cdk.CfnOutput(this, 'LogsBucketName', { description: 'S3 bucket for collected logs', value: this.logsBucket.bucketName, exportName: `${cdk.Stack.of(this).stackName}-LogsBucketName` });
    new cdk.CfnOutput(this, 'SSMAutomationRoleArn', { description: 'SSM Automation Role ARN', value: this.ssmAutomationRole.roleArn, exportName: `${cdk.Stack.of(this).stackName}-SSMAutomationRoleArn` });
    if (this.kmsKey) { new cdk.CfnOutput(this, 'EncryptionKeyArn', { description: 'KMS Encryption Key ARN', value: this.kmsKey.keyArn, exportName: `${cdk.Stack.of(this).stackName}-EncryptionKeyArn` }); }
    new cdk.CfnOutput(this, 'SOPBucketName', { description: 'S3 bucket for Standard Operating Procedures', value: this.sopBucket.bucketName, exportName: `${cdk.Stack.of(this).stackName}-SOPBucketName` });
  }

  private getToolSchemaDefinitions(): object[] {
    return [
      // =====================================================================
      // TIER 1: CORE OPERATIONS
      // =====================================================================
      {
        Name: 'collect',
        Description: 'Start ECS log collection from a container instance. Returns immediately with executionId for async polling. Supports idempotency tokens to prevent duplicate executions. Supports cross-region: auto-detects instance region or accepts explicit region parameter. CITATION: When presenting results, always cite the executionId and region returned.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID of the ECS container instance (e.g., i-0123456789abcdef0)' },
            idempotencyToken: { Type: 'string', Description: 'Optional token to prevent duplicate executions. If provided and a matching execution exists, returns the existing executionId.' },
            region: { Type: 'string', Description: 'AWS region where the instance runs (e.g., us-west-2). Optional: auto-detected from instance if omitted.' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            executionId: { Type: 'string', Description: 'SSM Automation execution ID for polling' },
            instanceId: { Type: 'string' },
            region: { Type: 'string' },
            status: { Type: 'string' },
            estimatedCompletionTime: { Type: 'string' },
            idempotent: { Type: 'boolean', Description: 'True if returning existing execution' },
            task: { Type: 'object', Description: 'Async task envelope for polling', Properties: { taskId: { Type: 'string' }, state: { Type: 'string', Description: 'running|completed|failed|cancelled' }, message: { Type: 'string' }, progress: { Type: 'integer', Description: '0-100 percent' } } },
          },
        },
      },
      {
        Name: 'status',
        Description: 'Get detailed status of a log collection execution including progress percentage, step details, and failure reasons. Automatically resolves the region where the execution was started. CITATION: Always cite executionId and status in your response.',
        InputSchema: {
          Type: 'object',
          Properties: {
            executionId: { Type: 'string', Description: 'The SSM Automation execution ID returned from collect' },
            includeStepDetails: { Type: 'boolean', Description: 'Include individual step status (default: true)' },
            region: { Type: 'string', Description: 'AWS region of the execution. Optional: auto-resolved from stored execution metadata if omitted.' },
          },
          Required: ['executionId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            automation: { Type: 'object', Properties: { executionId: { Type: 'string' }, status: { Type: 'string', Description: 'InProgress|Success|Failed|Cancelled' }, progress: { Type: 'integer' }, failureReason: { Type: 'string' }, stepDetails: { Type: 'array' } } },
            task: { Type: 'object', Properties: { taskId: { Type: 'string' }, state: { Type: 'string' }, message: { Type: 'string' }, progress: { Type: 'integer' } } },
          },
        },
      },
      {
        Name: 'validate',
        Description: 'Verify all expected files were extracted from the log bundle. Returns manifest with file counts, sizes, and missing patterns. Uses manifest.json when available for authoritative file inventory. CITATION: Cite fileCount, totalSizeHuman, and any missingPatterns.',
        InputSchema: {
          Type: 'object',
          Properties: {
            executionId: { Type: 'string', Description: 'SSM execution ID to validate' },
            instanceId: { Type: 'string', Description: 'Alternative: Instance ID to locate bundle' },
          },
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            complete: { Type: 'boolean' }, fileCount: { Type: 'integer' }, totalSize: { Type: 'integer' }, totalSizeHuman: { Type: 'string' },
            missingPatterns: { Type: 'array' }, foundPatterns: { Type: 'array' }, hasFindingsIndex: { Type: 'boolean' },
            manifest: { Type: 'array', Description: 'File list with key, fullKey, size, sizeHuman' },
          },
        },
      },
      {
        Name: 'errors',
        Description: 'Get pre-indexed error findings (fast path). Returns categorized errors by severity with finding_ids for citation. Each finding has a stable finding_id (F-001 format). Automatically recommends relevant SOPs based on detected error patterns (recommendedSOPs field). CITATION: Always cite finding_id and severity when referencing findings. Use finding_ids with summarize tool.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to get error summary for' },
            severity: { Type: 'string', Description: 'Filter by severity: critical, high, medium, low, info, or all (default: all). Legacy "warning" maps to "high".' },
            response_format: { Type: 'string', Description: '"concise" (default) returns finding_id/severity/pattern/file/count only. "detailed" includes full sample text and line numbers.' },
            pageSize: { Type: 'integer', Description: 'Number of findings per page (default: 50, max: 200)' },
            pageToken: { Type: 'string', Description: 'Opaque token for next page (from previous response nextPageToken)' },
            clusterContext: { Type: 'string', Description: 'ECS cluster name for baseline subtraction. When provided, findings seen 10+ times are annotated as baseline (normal operation).' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' },
            findings: { Type: 'array', Description: 'Array of findings with finding_id, severity, pattern, file, count' },
            totalFindings: { Type: 'integer' },
            summary: { Type: 'object', Description: 'Counts by severity: critical, high, medium, low, info' },
            hasMore: { Type: 'boolean' }, nextPageToken: { Type: 'string' },
            coverage_report: { Type: 'object', Description: 'files_scanned, files_skipped, scan_complete' },
            recommendedSOPs: { Type: 'array', Description: 'Auto-matched SOP runbooks based on detected error patterns. Each entry has sopName, relevanceScore, matchedKeywords, reason. Use get_sop to retrieve full SOP content.' },
          },
        },
      },
      {
        Name: 'read',
        Description: 'Read a chunk of a log file using byte-range streaming. NO TRUNCATION. Supports both byte-range and line-based reading for multi-GB files. Line-aligned: byte reads snap to newline boundaries. CITATION: Cite logKey, startByte, endByte, and totalSize.',
        InputSchema: {
          Type: 'object',
          Properties: {
            logKey: { Type: 'string', Description: 'The S3 key of the log file (from validate manifest)' },
            startByte: { Type: 'integer', Description: 'Starting byte offset (default: 0). Snaps forward to next newline.' },
            endByte: { Type: 'integer', Description: 'Ending byte offset (default: startByte + 1MB). Snaps forward to next newline.' },
            startLine: { Type: 'integer', Description: 'Alternative: Starting line number (1-based)' },
            lineCount: { Type: 'integer', Description: 'Number of lines to return when using startLine (default: 1000)' },
          },
          Required: ['logKey'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            logKey: { Type: 'string' }, content: { Type: 'string' },
            startByte: { Type: 'integer' }, endByte: { Type: 'integer' }, totalSize: { Type: 'integer' },
            hasMore: { Type: 'boolean' }, nextChunkToken: { Type: 'string' },
            truncated: { Type: 'boolean', Description: 'Always false — never truncates' },
            lineAligned: { Type: 'boolean' },
          },
        },
      },
      // =====================================================================
      // TIER 2: ADVANCED ANALYSIS
      // =====================================================================
      {
        Name: 'search',
        Description: 'Full-text regex search across all logs without truncation. Use for detailed investigation after reviewing error summary. CITATION: Cite finding_id (S-NNN format), file name, and match count for each result group.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to search logs for' },
            query: { Type: 'string', Description: 'Regex pattern to search for (e.g., "CannotPullContainerError|ResourceInitializationError")' },
            logTypes: { Type: 'string', Description: 'Comma-separated log types to search. Available types: ecs-agent, docker, containers, system, dmesg, networking, cgroups, metadata, gpu (default: all)' },
            maxResults: { Type: 'integer', Description: 'Maximum results per file (default: 100, max: 500)' },
            response_format: { Type: 'string', Description: '"concise" (default) or "detailed"' },
          },
          Required: ['instanceId', 'query'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' }, query: { Type: 'string' },
            filesSearched: { Type: 'integer' }, filesWithMatches: { Type: 'integer' }, totalMatches: { Type: 'integer' },
            results: { Type: 'array', Description: 'Array of {finding_id, file, fullKey, matchCount, matches[]}' },
            coverage_report: { Type: 'object' },
          },
        },
      },
      {
        Name: 'correlate',
        Description: 'Cross-file timeline correlation for incident analysis. Groups events by component, builds temporal clusters, and identifies potential root cause chains. Automatically recommends relevant SOPs based on correlated findings (recommendedSOPs field). CITATION: Cite finding_ids, confidence level, and any gaps reported.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to correlate events for' },
            timeWindow: { Type: 'integer', Description: 'Seconds around pivot event (default: 60)' },
            pivotEvent: { Type: 'string', Description: 'Event to correlate around (optional)' },
            components: { Type: 'array', Description: 'Components to include (optional)' },
            response_format: { Type: 'string', Description: '"concise" (default) or "detailed"' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' }, timeline: { Type: 'array' }, byComponent: { Type: 'object' },
            correlations: { Type: 'array' }, temporal_clusters: { Type: 'array' },
            potential_root_cause_chain: { Type: 'array' },
            confidence: { Type: 'string', Description: 'high|medium|low|none' },
            gaps: { Type: 'array' }, coverage_report: { Type: 'object' },
            recommendedSOPs: { Type: 'array', Description: 'Auto-matched SOP runbooks based on correlated findings. Each entry has sopName, relevanceScore, matchedKeywords, reason.' },
          },
        },
      },
      {
        Name: 'artifact',
        Description: 'Get secure presigned URL for large artifacts. Use for files too large to return directly. CITATION: Cite the logKey and expiresAt timestamp.',
        InputSchema: {
          Type: 'object',
          Properties: {
            logKey: { Type: 'string', Description: 'The S3 key of the artifact' },
            expirationMinutes: { Type: 'integer', Description: 'URL expiration in minutes (default: 15, max: 60)' },
          },
          Required: ['logKey'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            logKey: { Type: 'string' }, presignedUrl: { Type: 'string' }, expiresAt: { Type: 'string' }, sizeHuman: { Type: 'string' },
          },
        },
      },
      {
        Name: 'summarize',
        Description: 'Generate structured incident summary grounded in indexed findings. Pass finding_ids from errors tool to constrain summary to specific findings. Output includes grounded flag (true = all claims backed by finding_ids). Automatically recommends relevant SOPs based on findings and triage category (recommendedSOPs field). CITATION: Always cite the finding_ids that support each claim.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to summarize' },
            includeRecommendations: { Type: 'boolean', Description: 'Include remediation suggestions (default: true)' },
            finding_ids: { Type: 'array', Description: 'Optional list of finding_ids (F-001 format) from errors tool. When provided, summary is constrained to only these findings.' },
          },
          Required: ['instanceId', 'finding_ids'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' }, grounded: { Type: 'boolean' },
            unresolvedFindingIds: { Type: 'array' }, criticalFindings: { Type: 'array' },
            highFindings: { Type: 'array' }, affectedComponents: { Type: 'array' },
            recommendations: { Type: 'array' }, confidence: { Type: 'string' }, gaps: { Type: 'array' },
            recommendedSOPs: { Type: 'array', Description: 'Auto-matched SOP runbooks based on findings and triage category. Each entry has sopName, relevanceScore, matchedKeywords, reason. Use get_sop to retrieve full SOP content.' },
          },
        },
      },
      {
        Name: 'history',
        Description: 'List historical log collections for audit and comparison. Supports cross-region listing. CITATION: Cite executionId and status for each entry.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'Filter by instance ID (optional)' },
            maxResults: { Type: 'integer', Description: 'Maximum results (default: 20, max: 50)' },
            status: { Type: 'string', Description: 'Filter by status: Success, Failed, InProgress (optional)' },
            region: { Type: 'string', Description: 'AWS region to list executions from (default: Lambda region).' },
          },
        },
        OutputSchema: {
          Type: 'object',
          Properties: { executions: { Type: 'array' }, totalCount: { Type: 'integer' } },
        },
      },
      // =====================================================================
      // TIER 3: CLUSTER-LEVEL INTELLIGENCE
      // =====================================================================
      {
        Name: 'cluster_health',
        Description: 'Get a comprehensive health overview of an ECS cluster. Enumerates all container instances, checks SSM agent status, instance metadata (type, AZ, AMI, launch time), ECS agent connectivity, and flags unhealthy instances. The entry point before diving into individual instance investigation. CITATION: Cite clusterName, instance counts, and any unhealthy instanceIds.',
        InputSchema: {
          Type: 'object',
          Properties: {
            clusterName: { Type: 'string', Description: 'Name of the ECS cluster to inspect' },
            region: { Type: 'string', Description: 'AWS region of the cluster (auto-detected if omitted)' },
            includeSSMStatus: { Type: 'boolean', Description: 'Check SSM agent connectivity for each instance (default: true)' },
          },
          Required: ['clusterName'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            clusterName: { Type: 'string' }, totalInstances: { Type: 'integer' },
            healthyInstances: { Type: 'integer' }, unhealthyInstances: { Type: 'integer' },
            instances: { Type: 'array' },
          },
        },
      },
      {
        Name: 'compare_instances',
        Description: 'Diff error findings and health status between two or more container instances. Surfaces what is unique to a failing instance vs. common across all instances. CITATION: Cite instanceIds compared and unique findings per instance.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceIds: { Type: 'array', Description: 'List of 2+ EC2 instance IDs to compare (e.g., ["i-aaa", "i-bbb"])' },
            compareFields: { Type: 'string', Description: 'What to compare: "errors", "config", "all" (default: "all")' },
          },
          Required: ['instanceIds'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            commonFindings: { Type: 'array' }, uniqueFindings: { Type: 'object' }, insight: { Type: 'string' },
          },
        },
      },
      {
        Name: 'batch_collect',
        Description: 'Smart batch log collection with statistical sampling. Triages all container instances in a cluster, groups unhealthy instances into buckets by failure signature, and collects from representative samples. Use dryRun to preview before collecting. CITATION: Cite batchId, instance count, and sampling strategy used.',
        InputSchema: {
          Type: 'object',
          Properties: {
            clusterName: { Type: 'string', Description: 'Name of the ECS cluster' },
            region: { Type: 'string', Description: 'AWS region of the cluster (auto-detected if omitted)' },
            filter: { Type: 'string', Description: 'Instance filter: "all", "unhealthy", "disconnected" (default: "unhealthy")' },
            strategy: { Type: 'string', Description: '"sample" for smart sampling or "all" to collect from every filtered instance (default: "sample")' },
            samplesPerBucket: { Type: 'integer', Description: 'Instances to sample per failure bucket (default: 3, max: 5)' },
            maxTotalCollections: { Type: 'integer', Description: 'Hard cap on total collections (default: 15, max: 15)' },
            groupBy: { Type: 'string', Description: 'Grouping strategy: "auto", "az", "instance-type", "ami" (default: "auto")' },
            dryRun: { Type: 'boolean', Description: 'Preview which instances would be collected without starting (default: false)' },
          },
          Required: ['clusterName'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            batchId: { Type: 'string' }, executions: { Type: 'array' },
            totalInstances: { Type: 'integer' }, sampledInstances: { Type: 'integer' }, strategy: { Type: 'string' },
            task: { Type: 'object', Properties: { taskId: { Type: 'string' }, state: { Type: 'string' }, message: { Type: 'string' }, progress: { Type: 'integer' } } },
          },
        },
      },
      {
        Name: 'batch_status',
        Description: 'Poll status of multiple log collections at once. Returns consolidated view with allComplete boolean. Use after batch_collect to wait for all collections to finish. CITATION: Cite allComplete status and any failed executionIds.',
        InputSchema: {
          Type: 'object',
          Properties: {
            executionIds: { Type: 'array', Description: 'List of SSM execution IDs to poll (from batch_collect response)' },
            batchId: { Type: 'string', Description: 'Batch ID from batch_collect (alternative to executionIds)' },
          },
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            allComplete: { Type: 'boolean' }, executions: { Type: 'array' },
            successCount: { Type: 'integer' }, failedCount: { Type: 'integer' }, inProgressCount: { Type: 'integer' },
          },
        },
      },
      {
        Name: 'network_diagnostics',
        Description: 'Extract and structure networking info from collected log bundles. Parses iptables rules, Docker networking, route tables, DNS resolution, ENI attachment status, and security group config. Returns structured data instead of raw text. Automatically recommends relevant SOPs based on detected networking issues (recommendedSOPs field). CITATION: Cite instanceId and each section analyzed.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'The EC2 instance ID to analyze networking for' },
            sections: { Type: 'string', Description: 'Comma-separated sections: "iptables,docker,routes,dns,eni,security-groups" or "all" (default: "all")' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' }, sections: { Type: 'object' },
            assessment: { Type: 'string' }, issues: { Type: 'array' },
            confidence: { Type: 'string' }, gaps: { Type: 'array' },
            recommendedSOPs: { Type: 'array', Description: 'Auto-matched SOP runbooks based on detected networking issues. Each entry has sopName, relevanceScore, matchedKeywords, reason.' },
          },
        },
      },
      // =====================================================================
      // TIER 4: LIVE PACKET CAPTURE
      // =====================================================================
      {
        Name: 'tcpdump_capture',
        Description: 'Run tcpdump on an ECS container instance via SSM Run Command. Captures packets for a specified duration, generates protocol stats and decoded text, and uploads pcap/stats/text to S3. Supports capturing inside a specific ECS task network namespace via taskId. Returns commandId for async polling. CITATION: Cite commandId and instanceId.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'EC2 instance ID of the ECS container instance (required)' },
            durationSeconds: { Type: 'integer', Description: 'Capture duration in seconds (default: 120, max: 300)' },
            interface: { Type: 'string', Description: 'Network interface to capture on (default: "any")' },
            filter: { Type: 'string', Description: 'BPF filter expression (e.g., "port 443", "host 10.0.0.1")' },
            taskId: { Type: 'string', Description: 'ECS task ID to capture traffic for a specific container network namespace (optional)' },
            containerName: { Type: 'string', Description: 'Container name within the task (optional, uses first container if omitted)' },
            commandId: { Type: 'string', Description: 'If provided, polls status of an existing capture instead of starting a new one' },
            region: { Type: 'string', Description: 'AWS region where the instance runs (optional, auto-detected)' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            commandId: { Type: 'string', Description: 'SSM Command ID for polling' },
            instanceId: { Type: 'string' },
            status: { Type: 'string' },
            s3Key: { Type: 'string' },
            s3KeyTxt: { Type: 'string' },
            s3KeyStats: { Type: 'string' },
            s3Bucket: { Type: 'string' },
            task: { Type: 'object', Properties: { taskId: { Type: 'string' }, state: { Type: 'string' }, message: { Type: 'string' }, progress: { Type: 'integer' } } },
          },
        },
      },
      {
        Name: 'tcpdump_analyze',
        Description: 'Read and analyze a completed tcpdump capture from S3. Returns decoded packet text, protocol statistics (TCP/UDP/ICMP breakdown, port distribution, TCP flags), top talkers (source and destination IPs), and anomaly detection (high RST rates, retransmissions, SYN/RST ratios). CITATION: Cite commandId and any anomalies detected.',
        InputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string', Description: 'EC2 instance ID (required)' },
            commandId: { Type: 'string', Description: 'SSM Command ID from tcpdump_capture (optional — finds latest capture if omitted)' },
            section: { Type: 'string', Description: '"summary" (decoded packets), "stats" (protocol breakdown), "all" (default: "all")' },
            maxPackets: { Type: 'integer', Description: 'Max decoded packet lines to return (default: 500, max: 3000)' },
            filter: { Type: 'string', Description: 'Text filter on decoded lines (e.g., "SYN", "RST", "10.0.0.5")' },
          },
          Required: ['instanceId'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            instanceId: { Type: 'string' },
            commandId: { Type: 'string' },
            captureInfo: { Type: 'object' },
            statistics: { Type: 'object', Description: 'Protocol breakdown, port distribution, TCP flags, top talkers' },
            anomalies: { Type: 'array', Description: 'Detected anomalies with type, severity, and message' },
            decodedPackets: { Type: 'object', Description: 'Decoded packet lines with totalPackets, returnedPackets, truncated flag' },
            pcapDownloadUrl: { Type: 'string', Description: 'Presigned URL to download the raw pcap file (1 hour expiry)' },
          },
        },
      },
      // =====================================================================
      // SOP MANAGEMENT TOOLS
      // =====================================================================
      {
        Name: 'list_sops',
        Description: 'List all available Standard Operating Procedures (SOPs) in the S3 bucket. Returns name, size, and last modified date for each SOP.',
        InputSchema: {
          Type: 'object',
          Properties: {},
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            sops: { Type: 'array', Description: 'Array of {name, size, lastModified}' },
            count: { Type: 'integer' },
            bucket: { Type: 'string' },
          },
        },
      },
      {
        Name: 'get_sop',
        Description: 'Get a specific Standard Operating Procedure (SOP) by name. Returns the full content of the SOP file. Use list_sops first to discover available SOPs.',
        InputSchema: {
          Type: 'object',
          Properties: {
            sopName: {
              Type: 'string',
              Description: 'The name/key of the SOP file to retrieve (e.g., "runbooks/pod-crashloop.md")',
            },
          },
          Required: ['sopName'],
        },
        OutputSchema: {
          Type: 'object',
          Properties: {
            sop: { Type: 'object', Description: '{name, content, size, lastModified, contentType}' },
          },
        },
      },
    ];
  }

  private getUnzipLambdaCode(): string {
    return `
import json
import boto3
import zipfile
import tarfile
import io
import os
from datetime import datetime

s3_client = boto3.client('s3')
lambda_client = boto3.client('lambda')

FINDINGS_INDEXER_FUNCTION = os.environ.get('FINDINGS_INDEXER_FUNCTION', '')

def get_content_type(file_name):
    if file_name.endswith('.log') or file_name.endswith('.txt'):
        return 'text/plain'
    elif file_name.endswith('.json'):
        return 'application/json'
    elif file_name.endswith('.yaml') or file_name.endswith('.yml'):
        return 'text/yaml'
    return 'application/octet-stream'

def sanitize_archive_path(file_name):
    normalized = os.path.normpath(file_name)
    if normalized.startswith('..') or '/../' in normalized or normalized.startswith('/'):
        print(f"SECURITY: Skipping suspicious archive path: {file_name}")
        return None
    return normalized.lstrip('./')

def extract_zip(bucket, key, content):
    base_path = key[:-4]
    extract_prefix = f"{base_path}/extracted/"
    extracted_files = []
    with zipfile.ZipFile(io.BytesIO(content), 'r') as zip_ref:
        for file_info in zip_ref.infolist():
            if file_info.is_dir():
                continue
            file_name = sanitize_archive_path(file_info.filename)
            if file_name is None:
                continue
            file_content = zip_ref.read(file_info.filename)
            extract_key = f"{extract_prefix}{file_name}"
            s3_client.put_object(Bucket=bucket, Key=extract_key, Body=file_content, ContentType=get_content_type(file_name))
            extracted_files.append(extract_key)
            print(f"Extracted: {extract_key}")
    return extracted_files, extract_prefix

def extract_targz(bucket, key, content):
    if key.endswith('.tar.gz'):
        base_path = key[:-7]
    else:
        base_path = key[:-4]
    extract_prefix = f"{base_path}/extracted/"
    extracted_files = []
    with tarfile.open(fileobj=io.BytesIO(content), mode='r:gz') as tar_ref:
        for member in tar_ref.getmembers():
            if not member.isfile():
                continue
            file_name = sanitize_archive_path(member.name)
            if file_name is None:
                continue
            file_obj = tar_ref.extractfile(member)
            if file_obj is None:
                continue
            file_content = file_obj.read()
            extract_key = f"{extract_prefix}{file_name}"
            s3_client.put_object(Bucket=bucket, Key=extract_key, Body=file_content, ContentType=get_content_type(file_name))
            extracted_files.append(extract_key)
            print(f"Extracted: {extract_key}")
    return extracted_files, extract_prefix

def trigger_findings_indexer(bucket, prefix, file_count):
    if not FINDINGS_INDEXER_FUNCTION:
        print("No findings indexer function configured, skipping")
        return
    try:
        lambda_client.invoke(FunctionName=FINDINGS_INDEXER_FUNCTION, InvocationType='Event', Payload=json.dumps({'bucket': bucket, 'prefix': prefix, 'fileCount': file_count}))
        print(f"Triggered findings indexer for prefix: {prefix}")
    except Exception as e:
        print(f"Failed to trigger findings indexer: {str(e)}")

def generate_manifest(bucket, prefix, extracted_files, archive_key, archive_size):
    try:
        file_details = []
        for file_key in extracted_files:
            try:
                head = s3_client.head_object(Bucket=bucket, Key=file_key)
                relative_path = file_key.split('/extracted/')[-1] if '/extracted/' in file_key else file_key
                file_details.append({'key': relative_path, 'fullKey': file_key, 'size': head['ContentLength'], 'contentType': head.get('ContentType', 'application/octet-stream')})
            except Exception:
                file_details.append({'key': file_key.split('/extracted/')[-1] if '/extracted/' in file_key else file_key, 'fullKey': file_key, 'size': 0, 'contentType': 'unknown'})
        manifest = {'version': 2, 'generatedAt': datetime.utcnow().isoformat() + 'Z', 'archiveKey': archive_key, 'archiveSize': archive_size, 'totalFiles': len(extracted_files), 'totalSize': sum(f['size'] for f in file_details), 'files': file_details}
        manifest_key = f"{prefix}manifest.json"
        s3_client.put_object(Bucket=bucket, Key=manifest_key, Body=json.dumps(manifest, default=str), ContentType='application/json')
        print(f"Wrote manifest.json to {manifest_key} ({len(extracted_files)} files)")
    except Exception as e:
        print(f"Warning: Failed to generate manifest.json: {str(e)}")

def cleanup_old_bundles(bucket, current_archive_key, max_bundles_to_keep=2):
    """Delete old bundles for the same instance, keeping only the N most recent."""
    try:
        parts = current_archive_key.split('_')
        if len(parts) < 3 or not parts[0].startswith('e'):
            print(f"Cannot parse instance from key: {current_archive_key}, skipping cleanup")
            return
        prefix_type = parts[0]
        instance_id = parts[1]
        bundle_prefix = f"{prefix_type}_{instance_id}_"
        paginator = s3_client.get_paginator('list_objects_v2')
        archives = []
        for page in paginator.paginate(Bucket=bucket, Prefix=bundle_prefix):
            for obj in page.get('Contents', []):
                k = obj['Key']
                if k.endswith('.tar.gz') or k.endswith('.zip'):
                    archives.append({'key': k, 'last_modified': obj['LastModified']})
        if len(archives) <= max_bundles_to_keep:
            print(f"Only {len(archives)} bundles for {instance_id}, nothing to clean up")
            return
        archives.sort(key=lambda a: a['last_modified'], reverse=True)
        to_delete = archives[max_bundles_to_keep:]
        for old in to_delete:
            old_key = old['key']
            if old_key.endswith('.tar.gz'):
                extracted_prefix = old_key[:-7] + '/extracted/'
            elif old_key.endswith('.zip'):
                extracted_prefix = old_key[:-4] + '/extracted/'
            else:
                continue
            del_keys = []
            for page in paginator.paginate(Bucket=bucket, Prefix=extracted_prefix):
                for obj in page.get('Contents', []):
                    del_keys.append({'Key': obj['Key']})
            bundle_base = old_key.rsplit('.', 1)[0] if '.tar.' in old_key else old_key[:-4]
            for page in paginator.paginate(Bucket=bucket, Prefix=bundle_base):
                for obj in page.get('Contents', []):
                    del_keys.append({'Key': obj['Key']})
            del_keys.append({'Key': old_key})
            seen = set()
            unique_keys = []
            for dk in del_keys:
                if dk['Key'] not in seen:
                    seen.add(dk['Key'])
                    unique_keys.append(dk)
            if unique_keys:
                for i in range(0, len(unique_keys), 1000):
                    batch = unique_keys[i:i+1000]
                    s3_client.delete_objects(Bucket=bucket, Delete={'Objects': batch, 'Quiet': True})
                print(f"Cleaned up old bundle: {old_key} ({len(unique_keys)} objects deleted)")
        print(f"Bundle cleanup complete for {instance_id}: kept {max_bundles_to_keep}, deleted {len(to_delete)} old bundles")
    except Exception as e:
        print(f"Warning: Bundle cleanup failed (non-fatal): {str(e)}")

def lambda_handler(event, context):
    print(f"Received event: {json.dumps(event)}")
    for record in event.get('Records', []):
        bucket = record['s3']['bucket']['name']
        key = record['s3']['object']['key']
        if '/extracted/' in key:
            print(f"Skipping already extracted file: {key}")
            continue
        is_zip = key.lower().endswith('.zip')
        is_targz = key.lower().endswith('.tar.gz') or key.lower().endswith('.tgz')
        if not is_zip and not is_targz:
            print(f"Skipping unsupported file type: {key}")
            continue
        print(f"Processing archive: s3://{bucket}/{key}")
        try:
            response = s3_client.get_object(Bucket=bucket, Key=key)
            content = response['Body'].read()
            if is_zip:
                extracted_files, prefix = extract_zip(bucket, key, content)
            else:
                extracted_files, prefix = extract_targz(bucket, key, content)
            print(f"Successfully extracted {len(extracted_files)} files from {key}")
            generate_manifest(bucket, prefix, extracted_files, key, len(content))
            trigger_findings_indexer(bucket, prefix, len(extracted_files))
            cleanup_old_bundles(bucket, key, max_bundles_to_keep=2)
        except (zipfile.BadZipFile, tarfile.TarError) as e:
            print(f"Error: {key} is not a valid archive: {str(e)}")
        except Exception as e:
            print(f"Error processing {key}: {str(e)}")
            raise e
    return {'statusCode': 200, 'body': json.dumps({'message': 'Archive extraction complete'})}
`;
  }

  private getFindingsIndexerCode(): string {
    return `
import json
import boto3
import os
import re
from datetime import datetime

s3_client = boto3.client('s3')
LOGS_BUCKET = os.environ['LOGS_BUCKET_NAME']

# ECS-specific scannable file patterns
SCANNABLE_FILE_PATTERNS = [
    r'ecs[-_]agent',
    r'ecs[-_]init',
    r'docker[/.]',
    r'containerd[/-]log',
    r'dmesg',
    r'messages',
    r'secure',
    r'syslog',
    r'journal',
    r'containers/',
    r'container-logs',
    r'var_log/.*\\.log',
    r'networking',
]
SCANNABLE_REGEXES = [re.compile(p, re.IGNORECASE) for p in SCANNABLE_FILE_PATTERNS]

SKIP_FILE_PATTERNS = [
    r'sysctl', r'ethtool', r'ifconfig', r'conntrack\\.txt',
    r'pkglist', r'ps\\.txt', r'ps-threads', r'top\\.txt',
    r'allprocstat', r'mounts\\.txt', r'modinfo', r'iptables',
    r'metrics\\.json', r'\\.json$', r'\\.yaml$', r'\\.yml$',
    r'\\.conf$', r'\\.toml$', r'\\.service$',
    r'docker-info', r'docker-ps', r'docker-images',
    r'instance-', r'metadata',
]
SKIP_REGEXES = [re.compile(p, re.IGNORECASE) for p in SKIP_FILE_PATTERNS]

# ECS-specific error patterns for findings indexer
ERROR_PATTERNS = {
    'critical': [
        (r'(?i)agent.*connected.*false', 'ECS Agent disconnected'),
        (r'(?i)AGENT_DISCONNECTED', 'ECS Agent disconnected from cluster'),
        (r'(?i)failed.*register.*container.*instance', 'Container instance registration failed'),
        (r'(?i)CannotPullContainerError', 'Cannot pull container image'),
        (r'(?i)CannotPullECRContainerError', 'Cannot pull ECR container image'),
        (r'(?i)ResourceInitializationError', 'Resource initialization failed'),
        (r'(?i)TaskFailedToStart', 'Task failed to start'),
        (r'(?i)CannotStartContainerError', 'Cannot start container'),
        (r'(?i)CannotCreateContainerError', 'Cannot create container'),
        (r'(?i)ContainerRuntimeError', 'Container runtime error'),
        (r'(?i)pull.*access.*denied', 'Image pull access denied'),
        (r'(?i)repository.*does.*not.*exist', 'Repository does not exist'),
        (r'(?i)unauthorized.*authentication.*required', 'Authentication required'),
        (r'(?i)toomanyrequests.*Too Many Requests', 'Docker Hub rate limit'),
        (r'(?i)unable to pull secrets or registry auth', 'Secrets/registry auth failed'),
        (r'(?i)docker.*daemon.*not.*running', 'Docker daemon not running'),
        (r'(?i)OCI runtime create failed', 'OCI runtime create failed'),
        (r'(?i)no.*space.*left.*device', 'No space left on device'),
        (r'(?i)invoked oom-killer', 'OOM killer invoked'),
        (r'(?i)Out of memory: Kill', 'OOM kill'),
        (r'(?i)Memory cgroup out of memory', 'cgroup OOM'),
        (r'(?i)kernel.*panic', 'kernel panic'),
        (r'(?i)segfault', 'segfault'),
        (r'(?i)ENI.*allocation.*failed', 'ENI allocation failed'),
        (r'(?i)InsufficientFreeAddressesInSubnet', 'IP exhaustion'),
        (r'(?i)deployment circuit breaker.*triggered', 'Circuit breaker triggered'),
        (r'(?i)AccessDeniedException', 'Access denied'),
        (r'(?i)exit code 137', 'Container killed (OOM)'),
        (r'(?i)exit code 139', 'Container segfault'),
        (r'(?i)SpotInterruptionError', 'Spot interruption'),
    ],
    'warning': [
        (r'(?i)health.*check.*failed', 'Health check failed'),
        (r'(?i)UNHEALTHY', 'Container unhealthy'),
        (r'(?i)task.*stopped', 'Task stopped'),
        (r'(?i)Essential container.*exited', 'Essential container exited'),
        (r'(?i)service.*was unable to place a task', 'Task placement failure'),
        (r'(?i)connection.*refused', 'Connection refused'),
        (r'(?i)connection.*timeout', 'Connection timeout'),
        (r'(?i)TLS.*handshake.*timeout', 'TLS timeout'),
        (r'(?i)DNS.*failed', 'DNS resolution failed'),
        (r'(?i)memory.*pressure', 'Memory pressure'),
        (r'(?i)cpu.*throttl', 'CPU throttling'),
        (r'(?i)log.*driver.*error', 'Log driver error'),
        (r'(?i)awslogs.*error', 'awslogs driver error'),
        (r'(?i)docker.*restart', 'Docker restarted'),
        (r'(?i)is not authorized to perform', 'IAM permission denied'),
        (r'(?i)OOMKilled', 'Container OOMKilled'),
        (r'(?i)conntrack.*table.*full', 'Conntrack table full'),
    ],
    'info': [
        (r'(?i)level=(?:warn|warning)', 'log-level warning'),
        (r'(?i)DEPRECATION:', 'deprecation notice'),
        (r'(?i)context deadline exceeded', 'context deadline'),
        (r'(?i)retrying', 'retrying operation'),
    ],
}

COMPILED_PATTERNS = {}
for _sev, _pats in ERROR_PATTERNS.items():
    COMPILED_PATTERNS[_sev] = []
    for _pat, _desc in _pats:
        try:
            COMPILED_PATTERNS[_sev].append((re.compile(_pat), _desc))
        except re.error:
            pass

def is_scannable(filename):
    for skip_re in SKIP_REGEXES:
        if skip_re.search(filename):
            return False
    for scan_re in SCANNABLE_REGEXES:
        if scan_re.search(filename):
            return True
    if filename.endswith('.log') or filename.endswith('.txt'):
        log_dirs = ['ecs-agent', 'docker', 'var_log', 'kernel', 'system/messages']
        return any(d in filename for d in log_dirs)
    return False

def lambda_handler(event, context):
    print(f"Received event: {json.dumps(event)}")
    bucket = event.get('bucket', LOGS_BUCKET)
    prefix = event.get('prefix', '')
    if not prefix:
        return {'statusCode': 400, 'body': 'No prefix provided'}
    try:
        files_to_scan = []
        files_skipped = 0
        paginator = s3_client.get_paginator('list_objects_v2')
        for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
            for obj in page.get('Contents', []):
                key = obj['Key']
                if any(key.endswith(ext) for ext in ['.tar.gz', '.zip', '.gz', '.bin', '.so']):
                    continue
                if obj['Size'] > 5242880:
                    continue
                filename = key.split('/extracted/')[-1] if '/extracted/' in key else key
                if not is_scannable(filename):
                    files_skipped += 1
                    continue
                files_to_scan.append({'key': key, 'size': obj['Size']})
        print(f"Scanning {len(files_to_scan)} log files ({files_skipped} non-log files skipped)")
        all_findings = []
        for file_info in files_to_scan[:200]:
            findings = scan_file(bucket, file_info['key'])
            all_findings.extend(findings)
        deduplicated = deduplicate_findings(all_findings)

        # False positive suppression
        FALSE_POSITIVE_SUPPRESSIONS = [
            ('DNS.*failed', r'health[-.]?check|readiness|liveness', 'Health check DNS'),
            ('OOMKilled', r'stress[-.]?test|load[-.]?test|chaos', 'Stress test'),
            ('connection refused', r'127\\.0\\.0\\.1.*healthz', 'Local healthz'),
            ('TLS handshake', r'health[-.]?check', 'Probe TLS'),
        ]
        suppressed_count = 0
        filtered = []
        for f in deduplicated:
            suppressed = False
            pat = f.get('pattern', '')
            ctx = f.get('sample', '')
            for err_pat, fp_regex, reason in FALSE_POSITIVE_SUPPRESSIONS:
                if re.search(err_pat, pat, re.IGNORECASE):
                    if re.search(fp_regex, ctx, re.IGNORECASE):
                        suppressed = True
                        suppressed_count += 1
                        break
            if not suppressed:
                filtered.append(f)
        deduplicated = filtered

        for idx, finding in enumerate(deduplicated):
            finding['finding_id'] = f"F-{idx + 1:03d}"
            finding['evidence'] = {'source_file': finding.get('file', ''), 'full_key': finding.get('fullKey', ''), 'excerpt': finding.get('sample', '')[:500], 'line_range': {'start': finding.get('line', 0), 'end': finding.get('line', 0)}}

        # Multi-signal confirmation for critical findings
        pattern_files = {}
        for f in deduplicated:
            p = f.get('pattern', '')
            if p not in pattern_files:
                pattern_files[p] = set()
            pattern_files[p].add(f.get('file', ''))
        for f in deduplicated:
            if f.get('severity') == 'critical':
                sources = list(pattern_files.get(f.get('pattern', ''), set()))
                f['confirmation'] = {'signals': len(sources), 'confirmed': len(sources) >= 2, 'sources': sources[:5]}
                if len(sources) < 2:
                    f['severity_note'] = 'Single-source critical finding. Verify with additional log sources.'

        summary = {
            'critical': len([f for f in deduplicated if f.get('severity') == 'critical']),
            'high': len([f for f in deduplicated if f.get('severity') in ('warning', 'high')]),
            'medium': len([f for f in deduplicated if f.get('severity') == 'medium']),
            'low': len([f for f in deduplicated if f.get('severity') == 'low']),
            'info': len([f for f in deduplicated if f.get('severity') == 'info']),
        }
        total_files_in_bundle = len(files_to_scan) + files_skipped
        coverage = {'files_scanned': len(files_to_scan), 'total_files': total_files_in_bundle, 'coverage_pct': round(len(files_to_scan) / max(total_files_in_bundle, 1) * 100, 1), 'files_skipped': files_skipped, 'suppressed_false_positives': suppressed_count}
        index_data = {'index_version': 'v2', 'indexedAt': datetime.utcnow().isoformat(), 'prefix': prefix, 'coverage': coverage, 'filesScanned': len(files_to_scan), 'filesSkipped': files_skipped, 'findings': deduplicated[:500], 'summary': summary}
        index_key = f"{prefix}findings_index.json"
        s3_client.put_object(Bucket=bucket, Key=index_key, Body=json.dumps(index_data, default=str), ContentType='application/json')
        print(f"Wrote findings index to {index_key}")
        print(f"Summary: {summary}")
        return {'statusCode': 200, 'body': json.dumps({'message': 'Findings indexed', 'indexKey': index_key, 'summary': summary})}
    except Exception as e:
        print(f"Error indexing findings: {str(e)}")
        return {'statusCode': 500, 'body': str(e)}

def scan_file(bucket, key):
    findings = []
    try:
        response = s3_client.get_object(Bucket=bucket, Key=key, Range='bytes=0-1048575')
        content = response['Body'].read()
        try:
            content_str = content.decode('utf-8')
        except:
            content_str = content.decode('latin-1', errors='ignore')
        filename = key.split('/extracted/')[-1] if '/extracted/' in key else key
        lines = content_str.split('\\n')[:5000]
        for severity, compiled_list in COMPILED_PATTERNS.items():
            for regex, description in compiled_list:
                match_count = 0
                for i, line in enumerate(lines):
                    if regex.search(line):
                        findings.append({'file': filename, 'fullKey': key, 'severity': severity, 'pattern': description, 'line': i + 1, 'sample': line.strip()[:300]})
                        match_count += 1
                        if match_count > 50 or len(findings) > 200:
                            break
                if len(findings) > 200:
                    return findings
    except Exception as e:
        print(f"Error scanning {key}: {str(e)}")
    return findings

def deduplicate_findings(findings):
    seen = {}
    for finding in findings:
        dedup_key = f"{finding.get('file')}:{finding.get('pattern')}"
        if dedup_key not in seen:
            seen[dedup_key] = {**finding, 'count': 1, 'lines': [finding.get('line')], 'first_seen': finding.get('sample', '')[:50], 'last_seen': finding.get('sample', '')[:50]}
        else:
            seen[dedup_key]['count'] += 1
            if len(seen[dedup_key]['lines']) < 10:
                seen[dedup_key]['lines'].append(finding.get('line'))
            seen[dedup_key]['last_seen'] = finding.get('sample', '')[:50]
    severity_map = {'warning': 'high'}
    for entry in seen.values():
        old_sev = entry.get('severity', 'info')
        if old_sev in severity_map:
            entry['severity'] = severity_map[old_sev]
    severity_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4}
    return sorted(seen.values(), key=lambda x: (severity_order.get(x.get('severity'), 4), -x.get('count', 0)))
`;
  }

  /**
   * Returns the Client Secret Retriever Lambda function code
   */
  private getClientSecretRetrieverCode(): string {
    return `
import boto3
import json

def handler(event, context):
    try:
        if isinstance(event, str):
            event = json.loads(event)
        if 'Payload' in event:
            event = json.loads(event['Payload'])
        if event.get('RequestType') == 'Delete':
            return {'statusCode': 200, 'body': json.dumps({'ClientSecret': ''})}
        
        props = event.get('ResourceProperties', event)
        user_pool_id = props['UserPoolId']
        client_id = props['ClientId']
        
        cognito = boto3.client('cognito-idp')
        response = cognito.describe_user_pool_client(
            UserPoolId=user_pool_id, 
            ClientId=client_id
        )
        client_secret = response['UserPoolClient'].get('ClientSecret', '')
        
        return {
            'statusCode': 200, 
            'body': json.dumps({'ClientSecret': client_secret})
        }
    except Exception as e:
        print(f"Error: {str(e)}")
        return {'statusCode': 500, 'body': json.dumps({'Error': str(e)})}
`;
  }
}
